// WORLD

const GAME_WIDTH = 800;
const GAME_HEIGHT = 800;

const GRAVITY_DELTA_VELOCITY_Y = 0.4;

// GROUND

const GROUND_COLOR = "#222";

// PLAYER

const PLAYER_COLOR = "#fff";

const PLAYER_JUMP_VELOCITY_Y = -11;
const PLAYER_COOLDOWN_DURATION_MS = 500;
const PLAYER_JUMP_FUTURE_BUFFER_MS = 2000;

// SHURIKENS

const SHURIKEN_SLOW_COLOR = "#ff0"
const SHURIKEN_MED_COLOR = "#f00"
const SHURIKEN_FAST_COLOR = "#00f"

const SHURIKEN_WIDTH = 20;
const SHURIKEN_HEIGHT = 20;

const SHURIKEN_SLOW_VELOCITY_X = 2.5;
const SHURIKEN_MED_VELOCITY_X = 3;
const SHURIKEN_FAST_VELOCITY_X = 3.5;
